### PR TITLE
Backend: D3D12

### PR DESCRIPTION
**Pull request by Ohjurot**
I took some time to write a basic d3d12 backend for Nuklear. 
The backend was copy and pasted from d3d11 and then adopted to DirectX 12 by me. 
The backend supports everything included in the `main.c` example. Additional I implemented a system that allows the easy use of custom textures with the default nuklear shader. I have taken the freedom to add more comments than the original version featured to improve the readability of the way longer code.

This implements feature request #83 and #161

Looking forward for feedback, improvements, and a merge!

### CODE REVIEW

**Comment by Ohjurot** [comment]
@RobLoach I have made a short video on my nuklear d3d12 backend. Since nobody seems to feel addressed this might be sufficient. You can see me clone my branch, compile it and run the demo. Here is the [url](https://youtu.be/tOd0krEb5K0?t=95). So, if it is just for the point of verifying that everything works I hope this should be sufficient.

**Comment by dumblob** [comment]
Hi Ludwig, I'm also unable to test it myself for now. But I've taken a quick look at the source and it looks good to me. So I'm merging it (we're [not strict](https://github.com/Immediate-Mode-UI/Nuklear#reviewers-guide ) with PRs which do not concern `nuklear.h`).

And thanks for the video - very comprehensive. Appreciated!

Btw. once you'll finish your research into making Nuklear with GDI backend into a separate "full-featured" window, feel free to make a PR with it as another demo (if it won't be proprietary). Some people will definitely appreciate it.

**Comment by RobLoach** [comment]
Great work! I've added a link to the video tutorial in the wiki over at https://github.com/Immediate-Mode-UI/Nuklear/wiki/D3D-12

**Comment by Ohjurot** [comment]
Thank you! I have a nearly fully working demo of pure nuklear windows working (Also supporting multiple windows by removing the global state of the GDI backend). Its just a few changes to the GDI backend plus currently ~400 lines of C++ code. The demo would expose a `window` class that has overloadable methods for drawing, logic and events. Going to create a follow-up PR as soon as I'm going to have it in an "GitHub friendly" style.

**Pull request merged**
