### PR TITLE
Fix uninitialized variable warning

### PR DESCRIPTION
**Pull request by cxong**
Initialize num_len with a value to suppress warning

### CODE REVIEW

**Comment by Hejsil** [comment]
LGMT. You just need to bumb the version in [package.json](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/package.json), add this version to the [changelog](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/CHANGELOG) and run the `paq` script as specified in the [readme](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/Readme.md).

**Comment by Hejsil** [comment]
Also, just out of curiosity. What compiler throws this warning?

**Comment by cxong** [comment]
MSVC, and when you turn up the warnings I think

**Comment by Hejsil** [comment]
Forgot about this one. If you can rebase this on master and @dumblob approves then I'll merge this. Very sorry about neglecting this.

**Comment by dumblob** [comment]
I'm very sorry for being silent for so long here - I feel time goes against me :cry:.

Yes, this looks good to me if rebased. @cxong feel free to reopen and we'll merge soonish afterwards. Thanks @cxong !

**Pull request closed without merging**
