### PR TITLE
Added GitHub CI support

### PR DESCRIPTION
**Pull request by Nielsbishere**
Removed build status badge from travis and travis file.
Added proper GitHub CI build.

### CODE REVIEW

**Comment by dumblob** [comment]
Thanks, appreciated.

Could you please split this PR into two - one for CI and the other for the defines (which we'll discuss first as I'm currently unable to understand the added value :wink: - don't forget to change first the source files under `src/` and then run `src/paq.sh` - or follow `src/Readme.md` - which generates the final `nuklear.h` - it's a similar amalgamation as SQLite does).

I'll merge this CI PR immediately afterwards.

**Comment by dumblob** [comment]
@Nielsbishere do you think we could use some badges (e.g. https://github.com/badges/shields/issues/2574#issuecomment-559344943 )?

**Comment by Nielsbishere** [comment]
Yeah I found paq, I'm making a PR for paq.bat, so it's easier to run on windows.
I'll look into the shield thing.

**Comment by Nielsbishere** [comment]
https://github.com/apps/shields-deployment/
I think you can add this and then just update the readme.

**Comment by dumblob** [comment]
Oh, I'm dumb(lob) - there is very recent doc about badges on https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository . Sorry for the fuss.

**Comment by dumblob** [comment]
Badge done (though CI didn't trigger yet as it seems).

**Pull request merged**
