### PR TITLE
Include stdarg

### PR DESCRIPTION
**Pull request by riri**
`NK_INCLUDE_STANDARD_VARARGS` needs the va_list type from **stdarg.h**.
So like `NK_INCLUDE_STANDARD_IO` which includes **stdio.h**, this one should include **stdarg.h**

Sorry for the multiple commits, I forgot to update the documentation and to regenerate **nuklear.h** from src directory.

### CODE REVIEW

**Comment by Hejsil** [comment]
Looks good, but when editing `nuklear.h` and `src` we require that the version be bumped in [package.json](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/package.json) and [CHANGELOG](https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/CHANGELOG). Get this done and we can merge this 👍

**Comment by riri** [comment]
Version bumped to 4.02.3

**Comment by Hejsil** [comment]
Sorry, but one more very minor thing. You forgot to run the `paq` script after updating `CHANGELOG`

**Comment by riri** [comment]
Sorry, I hope I will be more attentive for my next contributions...
Header packed again

**Comment by Hejsil** [comment]
Np. This now also looks good :+1: This is small enough that I don't think we need another reviewer to look over it

**Pull request merged**
