### PR TITLE
Fix layout bounds not accounting for padding

### LINKED ISSUE #132: Padding is not correctly figured for the bottom of a window
Setting padding to, say, {20,20} works fine on the left, top, and right.  But if you then do nk_window_get_content_region(), you'll find that the height is 40 too high (e.g. 2 times the top padding).

I assume this is an error...

### PR DESCRIPTION
**Pull request by Hejsil**
fixes #132

This is not quite done. Currently having this funny bug in the node editor demo.
out

### CODE REVIEW

**Comment by ronaaron** [comment]
I get what looks correct in my own demo with

````  layout->bounds.h -= panel_padding.y;````

Not adjusting the bounds.y.  For some reason that looks already adjusted.

**Comment by Hejsil** [comment]
Do you have a header on your window? If so, then that would take up some room so it might look like padding is applied. With this change, the repro in #132 gives the same number for both width and height, which is correct for a window with no header. I'll look into this a little more later once I have more time (probably in a weeks time).

**Comment by ronaaron** [comment]
No, the flags are just NO_SCROLLBAR. I set the style.window.padding to [20,20] and the content_bounds with your change looks like it has a double-padding on the top of the window.

I changed the window.header.normal color to something obvious, and it doesn't show up so... no header AFAICT.

**Comment by Hejsil** [comment]
:thinking: Strange. I'd need a test case as I can't reproduce with my simple example:
```
ctx->style.window.padding.x = 50;
ctx->style.window.padding.y = 50;
if (nk_begin(ctx, "Demo", nk_rect(50, 50, 200, 200), NK_WINDOW_NO_SCROLLBAR))
{
    struct nk_rect rect = nk_window_get_content_region(ctx);
    printf("%f %f\n", rect.w, rect.h);
}
nk_end(ctx);
```
This prints `100,000000 100,000000` which is correct for this example.

**Comment by Hejsil** [comment]
Expanding the test case a little to show x and y:
```
ctx->style.window.padding.x = 50;
ctx->style.window.padding.y = 50;
if (nk_begin(ctx, "Demo", nk_rect(0, 0, 200, 200), NK_WINDOW_NO_SCROLLBAR))
{
    struct nk_rect rect = nk_window_get_content_region(ctx);
    printf("%f %f %f %f\n", rect.x, rect.y, rect.w, rect.h);
}
nk_end(ctx);
```

Prints `50,000000 50,000000 100,000000 100,000000` which is correct

**Comment by ronaaron** [comment]
It must be something odd w/ my code.  Not all that interesting, the fix looks proper.

**Comment by Hejsil** [comment]
Alright, I'll just look into the bug in the node editor demo then :+1:

**Review by RobLoach — CHANGES_REQUESTED** [review]
Sounds like some small changes in the demo remain?

**Comment by RobLoach** [comment]
@Hejsil This good to merge now? Thanks a lot!

**Comment by Hejsil** [comment]
@RobLoach Ooh shoot. I did not manage to fix the node_editor demo. I was looking into it earlier after I did a rebase but didn't find the cause

**Comment by RobLoach** [comment]
Revert it until it's fixed?

**Comment by Hejsil** [comment]
This seems like a bug in node_editor and not in nuklear, but not a 100% sure. We could also open an issue for this. I'll have another look at this whenever I have time over the holiday

**Pull request merged**
