### PR TITLE
Fix bug where width padding was applied twice

### PR DESCRIPTION
**Pull request by Hejsil**
Let me be the first to open a PR on this new repo :confetti_ball:
Copied from [here](https://github.com/vurtun/nuklear/pull/935)

Before:
image

After:
image

### CODE REVIEW

**Comment by dumblob** [comment]
>Let me be the first to open a PR on this new repo ￼

Congratulations :wink:

Before someone will dive into the review - with which backends did you test this? I'm expecting some differences (as I suspect some backends are buggy in this regard).

**Comment by dumblob** [comment]
Btw. are you willing to review PRs of others? If so, I'll invite you to become an organization member with admin rights.

**Comment by Hejsil** [comment]
Tested with the x11_xft backend. I'll try other backends when I get time :)

I'm not really interested in doing reviews at the moment. I'm also not too versed in nuklears codebase, so I don't think I'm qualified to review PRs :)

**Comment by Nielsbishere** [comment]
Looks useful!

**Comment by dumblob** [comment]
>Tested with the x11_xft backend. I'll try other backends when I get time :)

The x11_xft backend is quite a good no, so I'd like to merge this. But anyway I'd like to have this tested with at least one more common backend (e.g. glfw) and I don't have time for that right now. Anyone?

> I'm also not too versed in nuklears codebase, so I don't think I'm qualified to review PRs :)

Don't be so humble. It's not a rocket science - rather an opportunity to learn how others think about the topic and make the project thrive (as more people have more experience) and second to ensure formalities are met (e.g. version bumps, roughly code style, at least one review of code PRs, C89 compatibility, etc.).

**Comment by Hejsil** [comment]
I have confirmed that this problem and this fix applies to the `glfw_opengl3`, `x11_xft` and `x11` demo backends.

**Comment by Hejsil** [comment]
Here is a before and after from the gui I'm building with Nuklear

Before:
image

After:
image

**Comment by Hejsil** [comment]
Mind changed. I wouldn't mind being an organization member. Reviewing and merging smaller scale PR's would help this project along i imagine :)

**Comment by dumblob** [comment]
Great news - invitation sent (if you didn't get any, just ping me). I'd like to encourage the "everybody is an admin, not just member" culture (so you're welcome to send admin invitations yourself at your sole discretion - I myself always try to look at their PR reviews before sending an invitation).

I read your comments on the current PRs and very much thank you for the work!

Hm, I though also we could make the statement from https://github.com/Immediate-Mode-UI a bit more specific in this repo (currently it says `We review all PRs before merging. We require backwards compatibility of nuklear.h (unlike of backends/demos/examples), but we also like major version bumps.`). Do you think a checklist in README.md of common things to look for when reviewing PRs would make sense? Maybe something like:

Changes to `nuklear.h` (i.e. `src/` directory):
* try to merge just good stuff (the measure here is code quality, not time before merging)
* version bumps
* code style (at least roughly)
* at least one review of each PR from a different person
* C89 compatibility
* prefer copy over pointer for small structs (e.g. RGB color) for performance reasons
* ...

Changes to other stuff in this repo (e.g. backends):
* none of the above is a requirement
* use of modern technology slightly preferred (e.g. C11 instead of C89)
* merge even incomplete or slow or a bit messy stuff, but always comment on these deficiencies in the code directly (or make todo lists at the top of source files) - here the measure is the time (the sooner merged, the better)
* ...

**Comment by Hejsil** [comment]
Yea, these seem like good points that should at least be stated somewhere easily available (the Readme is probably the best place). This information both helps reviewers look for the right things and contributes getting their stuff merged faster.

**Comment by dumblob** [comment]
@Hejsil could you amend then the review "rules" with your ideas and put it to readme?

**Pull request merged**
