### PR TITLE
Strict c++17 now compiles

### PR DESCRIPTION
**Pull request by Nielsbishere**
Fixes issue https://github.com/Immediate-Mode-UI/Nuklear/issues/11

Now detecting if memcpy and memset are actually needed. And same goes for the vertex check (they check correctly now).

Paq.sh now automatically outputs to nuklear.h.

### CODE REVIEW

**Comment by dumblob** [comment]
Continuing discussion from #11:

Why is it needed to introduce yet another define? Couldn't we use `#ifdef NK_MEMSET` and `#ifdef NK_MEMCPY` directly as mentioned in https://github.com/Immediate-Mode-UI/Nuklear/issues/11#issuecomment-561688043 ?

**Comment by Nielsbishere** [comment]
Because the moment that ifdef is used, it is immediately defined.

**Comment by dumblob** [comment]
I mean, c89 supports `#ifdef NK_MEMSET == nk_memset`...

**Comment by Nielsbishere** [comment]
Does it? C++17 gave me an error on that.

**Comment by dumblob** [comment]
Right, `nk_memset` would get expanded to `0`, so that won't work. In that case, could you please rename `NK_DEFAULT_MEMCPY` to `NK_MEMCPY_BUILTIN` and `NK_DEFAULT_MEMSET` to `NK_MEMSET_BUILTIN`? It's usually better to use the same prefix if chaining anything.

**Comment by dumblob** [comment]
And because it changes `nuklear.h`, we should also bump version.

**Comment by Nielsbishere** [comment]
Okay, I'll get on it when I got time again

**Comment by Nielsbishere** [comment]
Fixed.

**Comment by dumblob** [comment]
One last little piece - the version info has to be updated also in https://github.com/Immediate-Mode-UI/Nuklear/blob/master/src/CHANGELOG :wink: (and `nuklear.h` regenerated).

**Comment by Nielsbishere** [comment]
Done.

**Comment by Nielsbishere** [comment]
Merged with the latest PR and udpated so it works with strict clang c++17 too.

**Comment by dumblob** [comment]
I'm sorry, didn't notice it before, but could you make `paq.bat` behave in a way, that it outputs no `CRLF`, but just `LF` line endings? `nuklear.h` was always with `LF` and I'd like it to stay so.

Thanks again for your effort!

**Comment by Nielsbishere** [comment]
Fixed @dumblob, python used 'print' which prints newline characters based on the current architecture. I set it to force linux line endings.

**Comment by Hejsil** [comment]
LGTM. Maybe just squash the commits into one, to keep the git history tidy :)

**Pull request closed without merging**
