### PR TITLE
Enable and fix most GCC warnings

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Review by RobLoach — APPROVED** [review]
This is fantastic!

**Review by Hejsil — APPROVED** [review]
Since there are changes in nuklear.h we need a version bump. Other than that this is some nice stuff :+1:

**Comment by dumblob** [comment]
Nice one! Please bump and it'll get merged!

Btw. @ccawley2011 would you want to review some our PRs? I'd like to send you an invitation to this org to increase the bus factor :wink:.

**Comment by RobLoach** [comment]
Here ya go! https://github.com/ccawley2011/Nuklear-1/pull/1

**Review by RobLoach — APPROVED** [review]

**Pull request merged**
