### PR TITLE
Added working filled and outlined arc drawing to GDI binding

### PR DESCRIPTION
**Pull request by bmuessig**
This PR is based on #385 and correctly implements (filled) arc drawing, as well as circle stroke drawing in GDI.
It also adds the select all keyboard shortcut.

### CODE REVIEW

**Comment by bmuessig** [comment]
grafik

**Comment by bmuessig** [comment]
The issue in the original PR was that the drawing commands use angles in radians, not degrees. The conversion caused incorrect coordinates to be fed to GDI.

**Comment by bmuessig** [comment]
I've just realized that there is one more glitch - probably introduced when adding the circle fix:

grafik

The corner dragging triangle is no longer filled black, when the circle is visible.

grafik

**Comment by bmuessig** [comment]
Filling now works correctly:

grafik

**Comment by RobLoach** [comment]
Thanks so much for fixing it up!

**Comment by bmuessig** [comment]
Thanks for merging!

**Pull request merged**
