### PR TITLE
Fix behaviour of checkbox (issue #222)

### PR DESCRIPTION
**Pull request by crazyBaboon**
this solution fixes the issue #222 of the checkbox for the default style.

### CODE REVIEW

**Comment by aganm** [comment]
Behaviour functions correctly.

image

It's not the checkbox that is inactive, it's the button.

The inactive checkbox is active, so it is colored.

**Comment by aganm** [comment]
Here, I printed the value of inactive to show that it indeed works correctly.

GIF 3-18-2021 2-32-10 AM

**Comment by crazyBaboon** [comment]
@aganm I have updated the issue description with pics, to avoid confusion.

**Comment by crazyBaboon** [comment]
As can be seen in issue #222, this is not a perfect solution, and also it breaks the use of styles.c

**Pull request closed without merging**
