### PR TITLE
Integrate the canvas example with the demos

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by RobLoach** [comment]
I assume this black triangle is not suppose to happen on Allegro.
Screenshot at 2021-12-16 12-30-15

**Comment by ccawley2011** [comment]
> I assume this black triangle is not suppose to happen on Allegro. Screenshot at 2021-12-16 12-30-15

This seems to be fixed with PR #379.

**Review by RobLoach — APPROVED** [review]
This is awesome. Really liking this canvas demo.

**Comment by dumblob** [comment]
Nice demo! LGTM, merging.

**Pull request merged**
