### PR TITLE
Fix checking hovering when window is minimized

### PR DESCRIPTION
**Pull request by YgorVasilenko**
ctx->current->bounds contains bounds of window and seems not being modified when window is minimized, thus bounds adjustment needed in case of minimized window.

### CODE REVIEW

**Review by Hejsil — APPROVED** [review]

**Comment by dumblob** [comment]
LGTM. Please bump version and regenerate `nuklear.h` with paq from this repo. Thanks!

**Comment by YgorVasilenko** [comment]
> This seems to make sense? But would you mind updating the version, and rebuilding nuklear.h?

Hi, I did rebase from main Nuklear repo master branch, please, check.

**Comment by dumblob** [comment]
Could you also bump version and then regenerate `nuklear.h` with `paq.sh`/`paq.bat`?

**Comment by RobLoach** [comment]
Fixed up C89, added verison, and rebuilt nuklear.h.

**Review by RobLoach — APPROVED** [review]
Seems pretty good now. Thanks a lot!

**Comment by dumblob** [comment]
Oops, didn't notice this one before I merged the semver syntax commit. Once you bump the version yet another time, just merge it immediately, thanks!

**Comment by RobLoach** [comment]
@dumblob No worries! Updated.

**Pull request merged**
