### PR TITLE
Fix nk_combo return type wrongly changed to nk_bool

### PR DESCRIPTION
**Pull request by aganm**

### CODE REVIEW

**Comment by aganm** [comment]
Also `nk_combo_begin` changed to nk_bool, this one should be nk_bool.

**Comment by dumblob** [comment]
@aganm please read our Reviewers' Guidelines and fix the missing bits before we'll dive into review :wink:.

@exchg could you please review so that we have at least two reviewers?

**Comment by exchg** [comment]
> @exchg could you please review so that we have at least two reviewers?

sure

**Comment by exchg** [comment]
looks like it's ok

**Comment by dumblob** [comment]
LGTM. Thanks for catching this inconsistency @exchg and for the second review!

**Pull request merged**
