### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Nielsbishere**
Updated links. Please move travis to Immediate-Mode-UI/nuklear.

### CODE REVIEW

**Comment by dumblob** [comment]
Speaking about Travis, I've heard, that the GitHub CI is much faster and adopts packages etc. quicker. We could than use it instead of Travis. What do you think? Didn't try that and have no idea how difficult that would be, but if you looked into that (at best as part of this PR), I'd be really glad.

**Comment by Nielsbishere** [comment]
Adding C/C++ CMake works on my own repo.
I've heard that build times can differ a lot for bigger builds. It can build for both linux and windows.
```yaml
name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Windows build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake build
      run: cmake . -G "Visual Studio 16 2019"
    - name: build
      run: cmake --build . -j 8
```
Though you aren't using cmake, so you'd run python instead.

**Comment by dumblob** [comment]
Thanks for the highlights. Would you want to add a plain `make` (not `cmake`) github CI support to this repo? If rather not, I'll merge this PR as is.

**Comment by Nielsbishere** [comment]
Never used make before. Best case scenario, you'd just have to generate a cpp file with the NK_IMPLEMENTATION define and include and then throw that to gcc or something. However, if you want to run the python script, you could do that too.

**Comment by dumblob** [comment]
Merged as is. Using plain `make` is important for ouf-of-box cross platform support.

**Pull request merged**
