### PR TITLE
nuklear_glfw_gl3.h without implementation

### PR DESCRIPTION
**Pull request by riri**
Using this header without the implementation is not possible because needed structs are not defined in the header only part. This PR solves this problem by making `struct nk_glfw` and `struct nk_glfw_device` public.

Note that a source implementing this backend still needs to include nuklear implementation too, because it uses some macros defined only in the implementation part of nuklear (i.e. `NK_MEMSET`). I have not been as deep as reviewing that part (not being sure of what should be done).

### CODE REVIEW

**Comment by riri** [comment]
I have just changed how to fix it. Instead of exposing the nk_glfw struct, I made it allocated on the heap by nk_glfw3_init(), and freed by nk_glfw3_shutdown().

That makes an interface change in the init function, but that's not a big deal.

**Comment by riri** [comment]
That makes sense too :) Would you merge the PR at the selected commit, or I have to push back myself on my fork?

**Comment by Hejsil** [comment]
It would be easiest for me if you dropped the commit on your fork. That way I can just do the merge through github :+1:

**Comment by riri** [comment]
Done :)

**Comment by Hejsil** [comment]
Thanks!

**Pull request merged**
