### PR TITLE
Fix off-by-one error in NK_INTERSECT

### PR DESCRIPTION
**Pull request by luknw**
Fixes intersect detection for the upper bound, see #18 for rationale.

### CODE REVIEW

**Comment by Nielsbishere** [comment]
Almost looks correct. But it should only apply for the lower x & y bounds, the upper should be excluded. For example if you'd have two cells next to each other (tightly packed), a click in the begin of the second cell shouldn't be included in the first cell.

**Comment by luknw** [comment]
@Nielsbishere I'm not entirely sure if I understand you correctly, please tell me if I'm wrong.
Do you mean that the two inequalities in `NK_INTERSECT` check the lower bound and the other two the upper bound? So, following this logic, `NK_INTERSECT` should look like this?
```C
#define NK_INTERSECT(x0, y0, w0, h0, x1, y1, w1, h1) \
    (!(((x1 > (x0 + w0)) || ((x1 + w1) <= x0) || (y1 > (y0 + h0)) || (y1 + h1) <= y0)))
```

**Comment by Nielsbishere** [comment]
You should probably test the scenario I explained; like have two cells next to each other without padding or anything in between. Clicking the exact first pixel of the second cell and the pixel before it. Two of those checks shouldn't use equal and two should, but I can't tell you which ones since I havent touched that code yet.

**Comment by luknw** [comment]
Ok, the logic in `NK_INTERSECT` is a bit convoluted, but I think your reasoning is wrong here and all the checks should use equal.

I tested this to be sure and when only two checks use equals, the intersect is still detected wrong. The reason why is because all the checks involve comparison with either first cell or second cell upper bound.

Let's say we swap the order in which we provide first cell and second cell to `NK_INTERSECT`. The result should stay the same, because we test the same two cells. If two inequalities use equals and the other two don't, the checks would produce different results depending on the order of the cells.

**Comment by Nielsbishere** [comment]
I mean the following:
cell 0 at 0,0->16,16
cell 1 at 16,0->32,16
If you click 16,0 it should only intersect 1.
If you click at 32,0 it should intersect none.

**Comment by luknw** [comment]
@Nielsbishere I've tested the layout you came up with and there's no difference regarding the inequalities. I've peeked in the code and mouse clicks aren't detected using `NK_INTERCEPT`, but `NK_INBOX` instead.

**Comment by dumblob** [comment]
I'd like to merge this, but I'll wait for the consensus as I want to avoid misunderstandings.

**Comment by Nielsbishere** [comment]
What is using NK_INTERSECT then? What do you need to change this for? Does NK_INBOX use the correct equation?

**Comment by luknw** [comment]
`NK_INTERSECT` detects if any two rectangles intersect. There are two types of usages in the codebase:
1. detect if drawn shape bounds intersect clip rectangle
1. detect if two windows intersect each other

I encountered the issue with the second type when I wanted to have two windows aligned side by side. When hovering a mouse over a window, the window should become active, but only when there isn't any other window intersecting it. When window is active, widgets inside that window should change color on mouse hover. Due to the bug, the tightly arranged windows don't become active on hover and the widgets don't change color.

You can see how this behavior looks like in the issue I've filed: #18 

When it comes to `NK_INBOX`, it uses the correct equation. It's defined as:
https://github.com/Immediate-Mode-UI/Nuklear/blob/a3f40348d572fad24af1e2d6c6b755171af481db/src/nuklear.h#L5402-L5404

You can see, that `NK_BETWEEN` has a non-strict inequality in the lower bound and a strict one in the upper bound.

**Comment by Nielsbishere** [comment]
Seems good then, pretty good fix

**Comment by luknw** [comment]
Ok, now when we have consensus, I'd like to propose one last tiny change. Let's simplify boolean expression inside `NK_INTERSECT` to get rid of `not` at the beginning.

**Comment by dumblob** [comment]
Let's do this. One last thing is to bump version (in `src/CHANGELOG` and in `package.json` and then regenerate `nuklear.h` as described in `src/Readme.md`) :wink:.

**Comment by luknw** [comment]
All right, I'll squash the changes into one commit.

**Comment by luknw** [comment]
Ok, should be ready to merge.

Btw. `package.json` has a repo set to `vurtun/nuklear`, shouldn't it be updated to `Immediate-Mode-UI/Nuklear`?

**Comment by dumblob** [comment]
>Btw. package.json has a repo set to vurtun/nuklear, shouldn't it be updated to Immediate-Mode-UI/Nuklear?

Good catch! Definitely needs an update. Feel free to do that in your PR. I'll merge this PR tomorrow at the latest.

**Comment by dumblob** [comment]
Hope this didn't get too tedious :wink:. Thanks!

**Pull request merged**
