### PR TITLE
Fix bug: Do not use pool before checking for NULL

### PR DESCRIPTION
**Pull request by fsb4000**

### CODE REVIEW

**Comment by dumblob** [comment]
@fsb4000 thanks for the catch! Before we'll review it, could you please check our [guidelines](https://github.com/Immediate-Mode-UI/Nuklear#reviewers-guide ) we'll use for that purpose and adjust your pull accordingly?

**Comment by fsb4000** [comment]
@dumblob Sure.  I checked all the items in the guidelines and I hope  I have completed them.

**Comment by Hejsil** [comment]
Looks good to me! :+1:

**Comment by dumblob** [comment]
Thank you all!

**Pull request merged**
