### PR TITLE
Horizontal rule

### PR DESCRIPTION
**Pull request by FrostKiwi**
grafik
This widget draws a horizontal rule line, like the classic html rule below this sentence.

---
This allows one to subdivide spaces a bit nicer. The last parameter of the widget is whether or not to apply rounding. If set to true, it will apply rounding, so the line always appears to be rounded off, the "pill shape".
The height is automatically determined by the current row height.
I didn't want to create a rule.c just for this, so I included it at the end of nuklear_window.c and the definition+documentation in Window section of nuklear.h.

### CODE REVIEW

**Comment by crazyBaboon** [comment]
Thanks @FrostKiwi ! This is looking good

**Review by RobLoach — APPROVED** [review]
I like this idea! Can provide some nice separation across widgets. Think we should make use of it in any of the example projects?

**Comment by RobLoach** [comment]
Actually, could we make use of the horizontal bar in one of the demos?

**Comment by yukyduky** [comment]
Could we get this merged? I can add an example to the demo if nobody wants to do it.

**Comment by FrostKiwi** [comment]
> Actually, could we make use of the horizontal bar in one of the demos?

Adding example to `OVERVIEW`

**Comment by FrostKiwi** [comment]
@RobLoach @yukyduky 
Added a showcase to the `Overview` kitchen-sink demo.
image

**Comment by RobLoach** [comment]
This is fantastic. Thanks so much, all.

**Pull request merged**
