### PR TITLE
create-tag github action for future tags

### PR DESCRIPTION
**Pull request by epsilon-0**
Closes: https://github.com/Immediate-Mode-UI/Nuklear/issues/136

Signed-off-by: Aisha Tammy <floss@bsd.ac>

### CODE REVIEW

**Comment by epsilon-0** [comment]
This is very useful for package maintainers to keep versions synced across different operating systems.

**Comment by RobLoach** [comment]
Seems like a good idea. Are we able to change to the new clib.json file?

**Comment by dumblob** [comment]
Yep, tagging shall follow `clib.json` (which is assumed to be in sync with the version in sources).

**Comment by RobLoach** [comment]
`        root: clib.json` should do it. Added.

**Pull request merged**
